/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#6750A4',
          light: '#7F67BE',
          dark: '#4F378B',
          container: '#EADDFF',
          fixed: '#EADDFF',
          'fixed-dim': '#D0BCFF',
        },
        secondary: {
          DEFAULT: '#625B71',
          light: '#7A7289',
          dark: '#4A4458',
          container: '#E8DEF8',
          fixed: '#E8DEF8',
          'fixed-dim': '#CCC2DC',
        },
        tertiary: {
          DEFAULT: '#7D5260',
          container: '#FFD8E4',
          fixed: '#FFD8E4',
          'fixed-dim': '#EFB8C8',
        },
        surface: {
          DEFAULT: '#FFFBFE',
          variant: '#E7E0EB',
          bright: '#FFFBFE',
          dim: '#DCD9DC',
          'container-lowest': '#FFFFFF',
          'container-low': '#F7F2FA',
          'container': '#F3EDF7',
          'container-high': '#ECE6F0',
          'container-highest': '#E6E1E5',
        },
        error: {
          DEFAULT: '#B3261E',
          light: '#F9DEDC',
          container: '#F9DEDC',
        },
        outline: {
          DEFAULT: '#79747E',
          variant: '#CAC4D0',
        },
        background: '#FFFBFE',
        foreground: '#1C1B1F',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#21005D',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#1D192B',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#31111D',
        'on-surface': '#1C1B1F',
        'on-surface-variant': '#49454F',
        'on-error': '#FFFFFF',
        'on-error-container': '#410E0B',
        'inverse-primary': '#D0BCFF',
        'inverse-surface': '#313033',
        'inverse-on-surface': '#F4EFF4',
      },
      fontFamily: {
        headline: ['Epilogue', 'system-ui', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
        'material': '16px',
      },
    },
  },
  plugins: [],
}
